        const sampleAgents = [
            {
                id: 'permit-license-management',
                name: 'Permit & License Management Agent Stack',
                category: 'Energy',
                shortDescription: 'Automates renewal and tracking of operational permits',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '⚡'
            },
            {
                id: 'field-service-dispatch',
                name: 'Field Service Dispatch Agent Stack',
                category: 'Energy',
                shortDescription: 'Optimizes technician dispatch based on skills, location, and urgency',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '⚡'
            },
            {
                id: 'regulatory-reporting',
                name: 'Regulatory Reporting Agent Stack',
                category: 'Energy',
                shortDescription: 'Auto-generates EPA/FERC/OSHA compliance documents',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '⚡'
            },
            {
                id: 'emission-tracking',
                name: 'Emission Tracking Agent Stack',
                category: 'Energy',
                shortDescription: 'Tracks, analyzes, and reports carbon emissions across operations',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '⚡'
            },
            {
                id: 'asset-maintenance-forecast',
                name: 'Asset Maintenance Forecast Agent Stack',
                category: 'Energy',
                shortDescription: 'Predicts equipment failure and schedules maintenance proactively',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '⚡'
            },
            {
                id: 'cart-abandonment-recovery',
                name: 'Cart Abandonment Recovery Agent Stack',
                category: 'B2C Sales',
                shortDescription: 'Follows up to convert abandoned carts to sales',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '🛒'
            },
            {
                id: 'returns-exchange',
                name: 'Returns & Exchange Agent Stack',
                category: 'B2C Sales',
                shortDescription: 'Automates return and refund workflows',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '🛒'
            },
            {
                id: 'sales-chat',
                name: 'Sales Chat Agent',
                category: 'B2C Sales',
                shortDescription: 'Improves sales team access to CRM information, product inventory, and pricing opportunities through an intelligent chat interface',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '🛒'
            },
            {
                id: 'customer-loyalty-rewards',
                name: 'Customer Loyalty & Rewards Agent Stack',
                category: 'B2C Sales',
                shortDescription: 'Manages loyalty programs and redemptions',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '🛒'
            },
            {
                id: 'omnichannel-engagement',
                name: 'Omnichannel Engagement Agent Stack',
                category: 'B2C Sales',
                shortDescription: 'Coordinates messaging across all customer channels',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '🛒'
            },
            {
                id: 'personalized-shopping-assistant',
                name: 'Personalized Shopping Assistant Stack',
                category: 'B2C Sales',
                shortDescription: 'Guides product discovery and purchase decisions',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '🛒'
            },
            {
                id: 'personalized-marketing',
                name: 'Personalized Marketing Agent Stack',
                category: 'Retail & CPG',
                shortDescription: 'Creates targeted campaigns based on customer behavior',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '🏪'
            },
            {
                id: 'returns-complaints-resolution',
                name: 'Returns & Complaints Resolution Agent Stack',
                category: 'Retail & CPG',
                shortDescription: 'Handles customer issues and return processing',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '🏪'
            },
            {
                id: 'store-associate-copilot',
                name: 'Store Associate Copilot Stack',
                category: 'Retail & CPG',
                shortDescription: 'Assists staff with product information and promotions',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '🏪'
            },
            {
                id: 'inventory-visibility',
                name: 'Inventory Visibility Agent Stack',
                category: 'Retail & CPG',
                shortDescription: 'Provides real-time inventory across all channels',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '🏪'
            },
            {
                id: 'supply-chain-disruption-alert',
                name: 'Supply Chain Disruption Alert Agent Stack',
                category: 'Retail & CPG',
                shortDescription: 'Notifies of disruptions and recommends alternatives',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '🏪'
            },
            {
                id: 'client-health-score',
                name: 'Client Health Score Agent Stack',
                category: 'Professional Services',
                shortDescription: 'Aggregates sentiment, usage, and satisfaction metrics',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '📊'
            },
            {
                id: 'proposal-copilot',
                name: 'Proposal Co-Pilot Agent Stack',
                category: 'Professional Services',
                shortDescription: 'Builds proposals from requirements and templates',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '📊'
            },
            {
                id: 'contract-risk-review',
                name: 'Contract Risk Review Agent Stack',
                category: 'Professional Services',
                shortDescription: 'Reviews contracts for risk and compliance issues',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '📊'
            },
            {
                id: 'resource-utilization',
                name: 'Resource Utilization Agent Stack',
                category: 'Professional Services',
                shortDescription: 'Matches staff skills to project requirements optimally',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '📊'
            },
            {
                id: 'time-entry-billing',
                name: 'Time Entry & Billing Agent Stack',
                category: 'Professional Services',
                shortDescription: 'Auto-logs time and generates accurate invoices',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '📊'
            },
            {
                id: 'deal-progression',
                name: 'Deal Progression Agent Stack',
                category: 'B2B Sales',
                shortDescription: 'Comprehensive deal progression intelligence powered by Dynamics 365 - featuring 10 specialized agents for stalled deal detection, health scoring, next actions, stakeholder analysis, activity gaps, pipeline velocity, competitive intelligence, risk assessment, win probability, and forecast accuracy',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '2.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '💼'
            },
            {
                id: 'proposal-generation',
                name: 'Proposal Generation Agent Stack',
                category: 'B2B Sales',
                shortDescription: 'Creates tailored proposals from prior successful deals',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '💼'
            },
            {
                id: 'account-intelligence',
                name: 'Account Intelligence Stack',
                category: 'B2B Sales',
                shortDescription: 'Comprehensive B2B account intelligence integrated with Microsoft Copilot Studio, Dynamics 365, Microsoft Graph, LinkedIn Sales Navigator, and Azure OpenAI. Provides stakeholder analysis, competitive intelligence, meeting prep, risk assessment, and deal tracking.',
                tags: ["B2B Sales", "Account Intelligence", "Copilot Studio", "Dynamics 365", "Microsoft Graph", "Azure OpenAI", "Sales Enablement", "Deal Intelligence", "Stakeholder Analysis", "Competitive Intelligence"],
                rating: 4.5,
                installs: 1000,
                version: '2.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '💼'
            },
            {
                id: 'win-loss-analysis',
                name: 'Win/Loss Analysis Agent Stack',
                category: 'B2B Sales',
                shortDescription: 'Analyzes closed deals for trends and insights',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '💼'
            },
            {
                id: 'sales-qualification',
                name: 'Sales Qualification Agent Stack',
                category: 'B2B Sales',
                shortDescription: 'Assesses leads and prioritizes by fit and intent',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '💼'
            },
            {
                id: 'supplier-risk-monitoring',
                name: 'Supplier Risk Monitoring Agent Stack',
                category: 'Manufacturing',
                shortDescription: 'Detects supply chain risks and recommends mitigation strategies',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '🏭'
            },
            {
                id: 'production-line-optimization',
                name: 'Production Line Optimization Agent Stack',
                category: 'Manufacturing',
                shortDescription: 'Analyzes production output and suggests efficiency improvements',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '🏭'
            },
            {
                id: 'inventory-rebalancing',
                name: 'Inventory Rebalancing Agent Stack',
                category: 'Manufacturing',
                shortDescription: 'Prevents overstock and stockouts through intelligent rebalancing',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '🏭'
            },
            {
                id: 'maintenance-scheduling',
                name: 'Maintenance Scheduling Agent Stack',
                category: 'Manufacturing',
                shortDescription: 'Reduces downtime by predicting equipment failures',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '🏭'
            },
            {
                id: 'order-status-communication',
                name: 'Order Status Communication Agent Stack',
                category: 'Manufacturing',
                shortDescription: 'Provides live updates on manufacturing and delivery status',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '🏭'
            },
            {
                id: 'competitive-intel',
                name: 'Competitive Intelligence Agent Stack',
                category: 'Development',
                shortDescription: 'Pulls competitor news, pricing, and feature updates',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '🚀'
            },
            {
                id: 'license-renewal-expansion',
                name: 'License Renewal & Expansion Agent Stack',
                category: 'Development',
                shortDescription: 'Flags expiring licenses and triggers customer success motions',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '🚀'
            },
            {
                id: 'product-feedback-synthesizer',
                name: 'Product Feedback Synthesizer Stack',
                category: 'Development',
                shortDescription: 'Analyzes customer feedback for feature requests and fixes',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '🚀'
            },
            {
                id: 'customer-onboarding',
                name: 'Customer Onboarding Agent Stack',
                category: 'Development',
                shortDescription: 'Walks users through setup and configuration processes',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '🚀'
            },
            {
                id: 'support-ticket-resolution',
                name: 'Support Ticket Resolution Agent Stack',
                category: 'Development',
                shortDescription: 'Resolves L1/L2 support tickets autonomously',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '🚀'
            },
            {
                id: 'staff-credentialing',
                name: 'Staff Credentialing Agent Stack',
                category: 'Healthcare',
                shortDescription: 'Automates tracking and renewal of healthcare staff credentials',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '🏥'
            },
            {
                id: 'clinical-notes-summarizer',
                name: 'Clinical Notes Summarizer Stack',
                category: 'Healthcare',
                shortDescription: 'Generates real-time summaries from provider-patient conversations',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '🏥'
            },
            {
                id: 'care-gap-closure',
                name: 'Care Gap Closure Agent Stack',
                category: 'Healthcare',
                shortDescription: 'Identifies missing screenings and automates patient outreach',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '🏥'
            },
            {
                id: 'patient-intake',
                name: 'Patient Intake & Scheduling Agent Stack',
                category: 'Healthcare',
                shortDescription: 'Automates patient intake, appointment coordination, and reminders to reduce no-shows. Integrates with major EHR systems and CRM platforms.',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '🏥'
            },
            {
                id: 'prior-authorization',
                name: 'Prior Authorization Automation Stack',
                category: 'Healthcare',
                shortDescription: 'Automates prior authorization processes by integrating with EHR systems and payer portals to speed up approvals and reduce manual interactions',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '🏥'
            },
            {
                id: 'mission-reporting-assistant',
                name: 'Mission Reporting Assistant Stack',
                category: 'Federal Government',
                shortDescription: 'Generates reports from classified and unclassified sources',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '🏛️'
            },
            {
                id: 'acquisition-support',
                name: 'Acquisition Support Agent Stack',
                category: 'Federal Government',
                shortDescription: 'Summarizes proposals and checks procurement compliance',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '🏛️'
            },
            {
                id: 'regulatory-compliance-fed',
                name: 'Regulatory Compliance Agent Stack',
                category: 'Federal Government',
                shortDescription: 'Monitors and reports FedRAMP/NIST compliance',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '🏛️'
            },
            {
                id: 'workforce-clearance-onboarding',
                name: 'Workforce Clearance & Onboarding Agent Stack',
                category: 'Federal Government',
                shortDescription: 'Streamlines background checks and training',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '🏛️'
            },
            {
                id: 'federal-grants-oversight',
                name: 'Federal Grants Oversight Agent Stack',
                category: 'Federal Government',
                shortDescription: 'Tracks grant spending, risk, and reporting',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '🏛️'
            },
            {
                id: 'financial-advisor-copilot',
                name: 'Financial Advisor Copilot Stack',
                category: 'Financial Services',
                shortDescription: 'Surfaces investment strategies and client insights',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '💰'
            },
            {
                id: 'fraud-detection-alert',
                name: 'Fraud Detection & Alert Agent Stack',
                category: 'Financial Services',
                shortDescription: 'Monitors transactions for suspicious activity patterns',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '💰'
            },
            {
                id: 'regulatory-compliance-fs',
                name: 'Regulatory Compliance Agent Stack',
                category: 'Financial Services',
                shortDescription: 'Ensures AML and GDPR compliance adherence',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '💰'
            },
            {
                id: 'customer-onboarding-fs',
                name: 'Customer Onboarding Agent Stack',
                category: 'Financial Services',
                shortDescription: 'Automates KYC and account setup processes',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '💰'
            },
            {
                id: 'underwriting-support',
                name: 'Underwriting Support Agent Stack',
                category: 'Financial Services',
                shortDescription: 'Pulls risk data and summarizes applications',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '💰'
            },
            {
                id: 'customer-sentiment-churn',
                name: 'Customer Sentiment & Churn Risk Agent Stack',
                category: 'Financial Services',
                shortDescription: 'Analyzes interactions to identify at-risk customers',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '💰'
            },
            {
                id: 'portfolio-rebalancing',
                name: 'Portfolio Rebalancing Agent Stack',
                category: 'Financial Services',
                shortDescription: 'Detects drift and recommends rebalancing actions',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '💰'
            },
            {
                id: 'claims-processing',
                name: 'Claims Processing Agent Stack',
                category: 'Financial Services',
                shortDescription: 'Automates insurance claim intake and processing',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '💰'
            },
            {
                id: 'loan-origination-assistant',
                name: 'Loan Origination Assistant Stack',
                category: 'Financial Services',
                shortDescription: 'Streamlines loan application and credit assessment',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '💰'
            },
            {
                id: 'wealth-insights-generator',
                name: 'Wealth Insights Generator Stack',
                category: 'Financial Services',
                shortDescription: 'Consolidates assets and generates comprehensive reports',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '💰'
            },
            {
                id: 'sales-coach',
                name: 'Sales Coach Stack',
                category: 'Utilities',
                shortDescription: 'AI-powered sales training and coaching. Provides personalized feedback, role-play scenarios, and performance improvement.',
                tags: ["automation", "ai", "enterprise", "sales_enablement"],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'Microsoft AI Solutions Team',
                sizeKb: 100,
                icon: '🔧'
            },
            {
                id: 'procurement-support',
                name: 'Procurement Support Stack',
                category: 'Utilities',
                shortDescription: 'Streamline procurement with automated vendor selection, PO creation, and spend analysis.',
                tags: ["automation", "ai", "enterprise", "procurement"],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'Microsoft AI Solutions Team',
                sizeKb: 100,
                icon: '🔧'
            },
            {
                id: 'customer-360',
                name: 'Customer 360 Stack',
                category: 'Utilities',
                shortDescription: 'Comprehensive customer data aggregation and insights platform. Unify customer data from all touchpoints to create actionable 360-degree customer profiles.',
                tags: ["customer-360", "cdp", "customer-intelligence", "analytics", "personalization", "data-aggregation", "predictive-analytics"],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'Microsoft AI Customer Intelligence Team',
                sizeKb: 100,
                icon: '🔧'
            },
            {
                id: 'cross-selling-opportunities',
                name: 'Cross-Selling Opportunities Stack',
                category: 'Utilities',
                shortDescription: 'Identify upsell and cross-sell opportunities based on customer behavior and purchase patterns.',
                tags: ["automation", "ai", "enterprise", "revenue_optimization"],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'Microsoft AI Solutions Team',
                sizeKb: 100,
                icon: '🔧'
            },
            {
                id: 'procurement-agent',
                name: 'Procurement Agent',
                category: 'Utilities',
                shortDescription: 'Streamlines procurement processes with Microsoft Teams integration for vendor management, purchase orders, and approval workflows',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '🔧'
            },
            {
                id: 'find-accurate-models',
                name: 'Find Accurate Models Stack',
                category: 'Utilities',
                shortDescription: 'Locate and recommend the most accurate AI models and configurations for specific use cases.',
                tags: ["automation", "ai", "enterprise", "ai_optimization"],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'Microsoft AI Solutions Team',
                sizeKb: 100,
                icon: '🔧'
            },
            {
                id: 'crm-bulk-data-creator',
                name: 'CRM Bulk Data Creator Stack',
                category: 'Utilities',
                shortDescription: 'Automated bulk data generation and import for CRM systems. Create thousands of test records, realistic customer data, and complex relationship structures.',
                tags: ["crm", "bulk-data", "dynamics-365", "test-data", "data-generation", "automation", "testing", "training"],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'Microsoft AI Solutions Team',
                sizeKb: 100,
                icon: '🔧'
            },
            {
                id: 'triage-bot',
                name: 'Triage Bot Stack',
                category: 'Utilities',
                shortDescription: 'Intelligent request prioritization and routing based on urgency, impact, and available resources.',
                tags: ["automation", "ai", "enterprise", "workflow_automation"],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'Microsoft AI Solutions Team',
                sizeKb: 100,
                icon: '🔧'
            },
            {
                id: 'it-ticket-management',
                name: 'IT Ticket Management Stack',
                category: 'Utilities',
                shortDescription: 'Automate IT support ticket routing, prioritization, and resolution with intelligent triage.',
                tags: ["automation", "ai", "enterprise", "it_operations"],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'Microsoft AI Solutions Team',
                sizeKb: 100,
                icon: '🔧'
            },
            {
                id: 'voice-to-crm',
                name: 'Voice to CRM Integration Stack',
                category: 'Utilities',
                shortDescription: 'A comprehensive voice-enabled CRM data entry solution that converts speech to text and automatically creates CRM records in Dynamics 365, ServiceNow, and other platforms.',
                tags: ["voice", "crm", "dynamics-365", "servicenow", "speech-to-text", "automation", "accessibility", "field-service", "sales", "customer-service"],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'Microsoft AI Accelerate Team',
                sizeKb: 100,
                icon: '🔧'
            },
            {
                id: 'simulation-sales',
                name: 'AI Sales Simulation Stack',
                category: 'Utilities',
                shortDescription: 'Advanced sales training and simulation platform. Practice sales scenarios, receive AI coaching, and improve closing rates through realistic simulations.',
                tags: ["sales-training", "simulation", "ai-coaching", "gamification", "performance", "training", "sales-enablement"],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'Microsoft AI Sales Excellence Team',
                sizeKb: 100,
                icon: '🔧'
            },
            {
                id: 'ai-customer-assistant',
                name: 'AI Customer Assistant Stack',
                category: 'Utilities',
                shortDescription: 'Intelligent customer service automation. Handle inquiries, resolve issues, and provide 24/7 support.',
                tags: ["automation", "ai", "enterprise", "customer_service"],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'Microsoft AI Solutions Team',
                sizeKb: 100,
                icon: '🔧'
            },
            {
                id: 'speech-to-crm',
                name: 'Speech to CRM Stack',
                category: 'Utilities',
                shortDescription: 'Convert voice conversations into structured CRM data. Automatically transcribe, analyze, and update CRM records from calls, meetings, and voice notes.',
                tags: ["speech-to-text", "crm", "voice", "automation", "nlp", "sales"],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'Microsoft AI Voice Intelligence Team',
                sizeKb: 100,
                icon: '🔧'
            },
            {
                id: 'email-drafting',
                name: 'Email Drafting Stack',
                category: 'Utilities',
                shortDescription: 'AI-powered email composition and automation. Generate professional emails, automate responses, and manage communication workflows.',
                tags: ["email", "ai-writing", "microsoft-365", "automation", "communication", "productivity", "nlp"],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'Microsoft AI Communications Team',
                sizeKb: 100,
                icon: '🔧'
            },
            {
                id: 'identify-discounts',
                name: 'Identify Discounts Stack',
                category: 'Utilities',
                shortDescription: 'Automatically identify and apply available discounts, promotions, and special pricing to maximize savings.',
                tags: ["automation", "ai", "enterprise", "pricing_optimization"],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'Microsoft AI Solutions Team',
                sizeKb: 100,
                icon: '🔧'
            },
            {
                id: 'product-reference',
                name: 'Product Reference Stack',
                category: 'Utilities',
                shortDescription: 'Comprehensive product information and recommendation system. Access detailed specs, comparisons, and intelligent search.',
                tags: ["automation", "ai", "enterprise", "product_intelligence"],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'Microsoft AI Solutions Team',
                sizeKb: 100,
                icon: '🔧'
            },
            {
                id: 'ask-hr',
                name: 'Ask HR Stack',
                category: 'Utilities',
                shortDescription: 'AI-powered HR assistant for employee questions about policies, benefits, and workplace matters.',
                tags: ["automation", "ai", "enterprise", "hr_automation"],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'Microsoft AI Solutions Team',
                sizeKb: 100,
                icon: '🔧'
            },
            {
                id: 'building-permit-processing',
                name: 'Building Permit Processing Agent Stack',
                category: 'State/Local Government',
                shortDescription: 'Reviews applications and tracks permit status',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '🏢'
            },
            {
                id: 'grants-management',
                name: 'Grants Management Agent Stack',
                category: 'State/Local Government',
                shortDescription: 'Automates grant intake, scoring, and tracking',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '🏢'
            },
            {
                id: 'foia-request-assistant',
                name: 'FOIA Request Assistant Stack',
                category: 'State/Local Government',
                shortDescription: 'Automates document search and redaction for FOIA',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '🏢'
            },
            {
                id: 'utility-billing-assistance',
                name: 'Utility Billing & Assistance Agent Stack',
                category: 'State/Local Government',
                shortDescription: 'Manages utility bills and assistance programs',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '🏢'
            },
            {
                id: 'citizen-service-request',
                name: 'Citizen Service Request Agent Stack',
                category: 'State/Local Government',
                shortDescription: '24/7 intake and routing of non-emergency issues',
                tags: [],
                rating: 4.5,
                installs: 1000,
                version: '1.0.0',
                author: 'RAPP Community',
                sizeKb: 100,
                icon: '🏢'
            },
        ];
